version: "3.9"

services:
  db:
    image: postgres:15
    container_name: transport_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: transport
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: ${transport_postgres_password}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres_user -d transport"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: transport_backend
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres_user:${transport_postgres_password}@db:5432/transport
      nswt_token: ${transport_nswt_token}
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

volumes:
  db_data:
